version: '3'

services:
  web:
    build: .
    command: mix phx.server
    environment:
      - MIX_ENV=dev
      - DATABASE_URL=ecto://postgres:postgres@postgres/football_dev
    volumes:
      - .:/app
    expose:
      - "4000"
    links:
      - postgres

  postgres:
    image: postgres:11
    volumes:
      - ./data/postgres:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  proxy:
    image: haproxy:1.9
    links:
      - web
    volumes:
        - ./haproxy:/haproxy-override
        - ./haproxy/haproxy.cfg:/usr/local/etc/haproxy/haproxy.cfg
    ports:
      - "80:80"

